import React,{useState} from"react";import{createRoot}from"react-dom/client";import{Search,Compass,GitCompare,UserRound,Trophy,Users,ArrowUpRight,Heart,Target}from"lucide-react";import"./styles.css";
const artists=[{name:"Saïf",city:"Cavaillon",listeners:"—",growth:"+",scores:{Flow:8.5,"Écriture":8.5,"Maîtrise vocale":8.5,Punchlines:8,Storytelling:7.5,Polyvalence:8,"Univers musical":9},tags:["Rap","Mélodique"],emerging:true},{name:"Lagui",city:"Marseille",listeners:"—",growth:"+",scores:{Flow:8,"Écriture":7.5,"Maîtrise vocale":8.5,Punchlines:7.5,Storytelling:7,Polyvalence:7.5,"Univers musical":8.5},tags:["Trap","Mélodique"],emerging:true}];
const nav=[["Accueil",Compass],["Artistes",Users],["Scout",Search],["Comparer",GitCompare],["Micro d'Or",Trophy],["Toi",UserRound]];
function Radar({scores}){let e=Object.entries(scores),c=100,r=72,pts=e.map(([_,v],i)=>{let a=-Math.PI/2+i*2*Math.PI/e.length,d=r*v/10;return[c+Math.cos(a)*d,c+Math.sin(a)*d].join(",")}).join(" ");return <svg viewBox="0 0 200 200" className="radar">{[2,4,6,8,10].map(v=><circle key={v} cx="100" cy="100" r={r*v/10}/>)}<polygon points={pts}/></svg>}
function App(){const[page,setPage]=useState("Accueil"),[selected,setSelected]=useState(artists[0]);return <div><header><b className="brand">MUSIQUE</b><nav>{nav.map(([n,I])=><button className={page===n?"active":""} onClick={()=>setPage(n)}><I size={16}/>{n}</button>)}</nav><button className="avatar">N</button></header><main>{page==="Accueil"&&<><section className="hero"><span>LA BASE DU RAP FRANCOPHONE</span><h1>Comprendre. Découvrir.<br/>Comparer.</h1><div className="search"><Search/><input placeholder="Rechercher un artiste, un projet, un morceau…"/></div></section><Section title="À surveiller" sub="Des profils à découvrir avant tout le monde">{artists.map(a=><ArtistCard a={a} open={()=>{setSelected(a);setPage("Artistes")}}/>)}</Section><Section title="Explorer autrement" sub="La popularité ne raconte pas toute l'histoire"><div className="feature"><Target/><div><b>Scout</b><p>Filtre les artistes par audience et capacités artistiques.</p></div><ArrowUpRight/></div></Section></>}
{page==="Artistes"&&<Profile a={selected}/>}
{page==="Scout"&&<><Title t="Scout" s="Trouve les artistes qui correspondent à tes critères."/><div className="filters"><label>Flow minimum <b>8</b><input type="range" min="0" max="10" step=".5" defaultValue="8"/></label><label>Univers musical <b>8</b><input type="range" min="0" max="10" step=".5" defaultValue="8"/></label></div><Section title="Résultats" sub="Popularité et capacité artistique restent séparées">{artists.map(a=><ArtistCard a={a} open={()=>{setSelected(a);setPage("Artistes")}}/>)}</Section></>}
{page==="Comparer"&&<><Title t="Comparer" s="Deux profils. Les données parlent, à toi de conclure."/><div className="compare">{artists.map(a=><ProfileMini a={a}/>)}</div></>}
{page==="Micro d'Or"&&<><Title t="Micro d'Or" s="Les distinctions annuelles du rap francophone."/><div className="gold"><Trophy/><span>MICRO D'OR · 2026</span><h2>Une année. Cinq finalistes.<br/>Un jury indépendant.</h2><p>Nommés · Jury · Résultats · Archives</p></div></>}
{page==="Toi"&&<><Title t="Toi" s="Ton identité musicale."/><div className="you"><div className="bigAvatar">N</div><h2>Ness</h2><span>Membre · 2026</span><h3>Ton Top 3</h3><div className="empty">Choisis les 3 artistes qui te représentent.</div><h3>Ton pari</h3><div className="bet"><Target/><div><b>Pas encore de pari</b><p>Mise sur un artiste émergent avant son envol.</p></div></div></div>}</main></div>}
function Title({t,s}){return <div className="title"><h1>{t}</h1><p>{s}</p></div>}
function Section({title,sub,children}){return <section className="section"><div><h2>{title}</h2><p>{sub}</p></div><div className="grid">{children}</div></section>}
function ArtistCard({a,open}){return <button className="artist" onClick={open}><div className="artistpic">{a.name[0]}</div><div><h3>{a.name}</h3><p>{a.city} · {a.tags.join(" · ")}</p><span>{a.scores["Univers musical"]}/10 univers</span></div><ArrowUpRight/></button>}
function Profile({a}){return <><div className="profileHead"><div className="portrait">{a.name[0]}</div><div><span>ARTISTE · ÉVALUATION PROVISOIRE</span><h1>{a.name}</h1><p>{a.city} · {a.tags.join(" · ")}</p><div className="actions"><button><Heart/>Suivre</button><button><Target/>Miser</button><button><GitCompare/>Comparer</button></div></div></div><div className="profileGrid"><div><h2>Profil artistique</h2><Radar scores={a.scores}/></div><div className="scores">{Object.entries(a.scores).map(([k,v])=><div><span>{k}</span><b>{v}</b><small>/10</small></div>)}</div></div><p className="note">Les notes sont éditoriales et décrivent un profil artistique. Elles ne constituent pas une note générale.</p></>}
function ProfileMini({a}){return <div className="mini"><div className="artistpic">{a.name[0]}</div><h2>{a.name}</h2><Radar scores={a.scores}/>{Object.entries(a.scores).map(([k,v])=><p><span>{k}</span><b>{v}</b></p>)}</div>}
createRoot(document.getElementById("root")).render(<App/>);